export const GET_GLOBAL_COVID_INFO = 'GET_GLOBAL_COVID_INFO';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY_INFO = 'GET_COUNTRY_INFO';
export const INFO_LOADING = 'INFO_LOADING';
export const INFO_FETCH_SUCCESS = 'INFO_FETCH_SUCCESS';
export const INFO_FETCH_FAILURE = 'INFO_FETCH_FAILURE';
